name: ml-server
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.7.3
  - ipython=7.5.0
  - pillow
  - flask
  - waitress
  - jsonpickle
  - numpy
  - tqdm
  - opencv
  - tqdm
  # optional
  - pandas
  - pytorch=1.6.0
  # - torchvision
  - fastai
  # pip
  - pip
  - pip:
    - imutils
    - sklearn
    - tesserocr
    - pytesseract
    - imageio
    - tabulate
    - gdown
    - ray
    - ray[tune]
    - ray[debug]