name: ml-server
channels:
  - conda-forge
  - fastai
  - pytorch
dependencies:
  - python=3.7.3
  - ipython=7.5.0
  - pillow
  - flask
  - waitress
  - jsonpickle
  - numpy
  - tqdm
  - opencv
  # optional
  # - pytorch-cpu
  # - torchvision-cpu
  # - fastai
  # pip
  - pip
  - pip:
    - imutils
    - tesserocr
