version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # volumes:
    #   - "/c/Users/domin/Documents/GitHub/ocr-benchmark:/code:rw"