version: '3.5'
services:
  web:
    build:
      context: .
      shm_size: '2gb' # <-- this will set the size when BUILDING
    shm_size: '2gb' # <-- when RUNNING 
    security_opt:
      - seccomp:unconfined
    ports:
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - "~/GitHub/ocr-benchmark:/code:rw"